allti logo
A-Love-Letter-to-Infinity/Infinity-Station-14 pull request #9
Opened 2024-10-16 17:17 UTC by Lyndomen

## About the PR
 Take thy form from off my door!

## Why / Balance
no

## Technical details
image

## Media
16x16 logo cant hurt you
![image](https://github.com/user-attachments/assets/cae6ef3c-6df6-44b6-ae36-e35829eaef28)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**
:cl:
- add: mail
-->

2024-10-16 17:19 UTC, Lyndomen commented
todo: new real logo eventually

2024-10-16 18:58 UTC, MilonPL approved these changes

2024-10-16 19:00 UTC, MilonPL requested changes
you need to remove or change icon.ico, icon.svg and logo.svg because we're changing the attributions

2024-10-16 19:00 UTC, MilonPL commented on Resources/Textures/Logo/logo.ico
should be icon.ico

2024-10-16 19:16 UTC, Lyndomen commented on Resources/Textures/Logo/logo.ico
real not fake

2024-10-16 19:19 UTC, MilonPL commented on Resources/Textures/Logo/icon-license.txt
> +allti.xcf
what the fuck is allti.xcf

2024-10-16 20:20 UTC, Lyndomen commented on Resources/Textures/Logo/icon-license.txt
> +allti.xcf
Mine

2024-10-16 20:25 UTC, MilonPL commented on Resources/Textures/Logo/icon-license.txt
> +allti.xcf
ok but it's not in the scope of this PR so doesn't need to be included in the license

2024-10-17 22:00 UTC, MilonPL approved these changes
surely nothing can go wrong

2024-10-18 17:12 UTC, Lyndomen commented
Merge my pr.gif

2024-10-19 18:54 UTC, merged